### ISSUE TITLE
Add Support Moba Chinese

### ISSUE THREAD

**Issue by tetsuki02** [RazTools/Studio#9]
Please Add Support Moba Chinese Like :
- Mobile Legends Chinese
- King OF Glory
- Etc

**Comment by tetsuki02** [comment]
[Hero.zip](https://github.com/RazTools/Studio/files/12287409/Hero.zip)
This Sir..
Hope You Can Open It. Very Thank's ^_^

**Comment by Razmoth** [comment]
Greetings, 

Will try to check later.

**Comment by tetsuki02** [comment]
hope you can add it sir ^_^

**Comment by WollieWoltaz** [comment]
Or maybe even Arena of Valor, the files are zstd compression according to this topic:
https://github.com/h3x4n1um/AoV-Zstd
They managed to compress and decompress files but this will still not work with Studio. (I was hopefull because in the newest release you added zstd support) Hopefully you can add support for it after all
Here are some sample files:
https://mega.nz/file/HQNE2RYS#G9QDYV8cCrMpilXeqB8xWyWusnQ1XxmlWQ83yR1A7QU

**Comment by tetsuki02** [comment]
> Or maybe even Arena of Valor, the files are zstd compression according to this topic: https://github.com/h3x4n1um/AoV-Zstd They managed to compress and decompress files but this will still not work with Studio. (I was hopefull because in the newest release you added zstd support) Hopefully you can add support for it after all Here are some sample files: https://mega.nz/file/HQNE2RYS#G9QDYV8cCrMpilXeqB8xWyWusnQ1XxmlWQ83yR1A7QU

i dont how to fix it,,
but can you test my file ?

**Comment by Razmoth** [comment]
Greetings,

There's a separate tool that support this kind of encryption [here](https://github.com/ProtoUnite/UntieUnite)

Just load the file and call `Dumper.DecryptAssetBundle` with `AssetFormat.Switch` as shown below, it should decrypt fine.

![image](https://github.com/RazTools/Studio/assets/32140579/6229c53a-f2b7-473f-94b7-664f11a24b65)

The output will be normal unity file.
